FROM jenkins/jenkins:lts

USER root

# Install Docker CLI + curl
RUN apt-get update && apt-get install -y \
    docker.io \
    curl \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# Install kubectl (match your kind cluster)
RUN curl -L -o /usr/local/bin/kubectl \
    https://dl.k8s.io/release/v1.32.2/bin/linux/amd64/kubectl \
 && chmod +x /usr/local/bin/kubectl

USER jenkins
