apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-cicd-demo
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: jenkins-cicd-demo
  template:
    metadata:
      labels:
        app: jenkins-cicd-demo
    spec:
      containers:
        - name: app
          image: jenkins-cicd-demo-project:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
